siteTitle = "K97 - Online Journal"
siteAuthor = "Karthikeyan Rajendran"
siteDescr = "An online journal of observations & learning about everything related to tech"

# siteTelegramUrl = "#"
siteTwitterUrl = "http://www.twitter.com/k97ind"
siteGithubUrl = "http://www.twitter.com/k97"
# siteEmailUrl = "#"
# siteRssUrl = "#"
# siteVkUrl = "#"

linkPrefix = "/gatsby-starter-lumen"
